CREATE TABLE IF NOT EXISTS `llx_lmdbadvancedproject_customer_invoice_parts` (
  `rowid` integer AUTO_INCREMENT PRIMARY KEY NOT NULL,
  `ref` varchar(128) DEFAULT NULL,
  `date` datetime DEFAULT NULL,
  `datep` date DEFAULT NULL,
  `qty` double(24,8) NOT NULL DEFAULT 0.00000000,
  `total_ht` double(24,8) NOT NULL DEFAULT 0.00000000,
  `total_ttc` double(24,8) NOT NULL DEFAULT 0.00000000,
  `input_mode` varchar(16) NOT NULL DEFAULT 'amount',
  `label` varchar(255) DEFAULT NULL,
  `fk_soc` integer NOT NULL,
  `fk_projet` integer NOT NULL,
  `fk_facture` integer NOT NULL,
  `fk_facture_det` integer NOT NULL,
  `entity` integer NOT NULL DEFAULT 1,
  `note` text DEFAULT NULL,
  `datec` datetime DEFAULT NULL,
  `tms` timestamp DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `fk_user_author` integer DEFAULT NULL,
  `fk_user_modif` integer DEFAULT NULL,
  UNIQUE KEY `uk_lmdbadvproj_custinvpart_project_line` (`fk_projet`, `fk_facture_det`),
  KEY `idx_lmdbadvproj_custinvpart_project` (`fk_projet`),
  KEY `idx_lmdbadvproj_custinvpart_invoice` (`fk_facture`),
  KEY `idx_lmdbadvproj_custinvpart_line` (`fk_facture_det`),
  KEY `idx_lmdbadvproj_custinvpart_soc` (`fk_soc`),
  KEY `idx_lmdbadvproj_custinvpart_entity` (`entity`)
) ENGINE=innodb DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
